<<<<<<< HEAD
cars_checklist.headlights_high, 
cars_checklist.headlights_low, 
cars_checklist.parkinglights_front, 
cars_checklist.turnsignals_front, 
cars_checklist.taillights, 
cars_checklist.turnsignals_rear, 
cars_checklist.brakelights, 
cars_checklist.backup_lights, 
cars_checklist.licensetabs_expiration, 
cars_checklist.sparetirepressure, 
cars_checklist.currenttirepressure_lf, 
cars_checklist.currenttirepressure_rf, 
cars_checklist.currenttirepressure_lr, 
cars_checklist.currenttirepressure_rr, 
cars_checklist.finaltirepressure_lf, 
cars_checklist.finaltirepressure_rf, 
cars_checklist.finaltirepressure_lr, 
cars_checklist.finaltirepressure_rr, 
cars_checklist.tirecondition_lf, 
cars_checklist.tirecondition_rf, 
cars_checklist.tirecondition_lr, 
cars_checklist.tirecondition_rr, 
cars_checklist.wipercondition, 
cars_checklist.airfiltercondition, 
cars_checklist.brakefluid, 
cars_checklist.powersteeringfluid, 
cars_checklist.transmissionfluid, 
cars_checklist.oillevel, 
cars_checklist.washerfluid, 
cars_checklist.coolantlevel, 
cars_checklist.coolantlevel_strength, 
cars_checklist.radiatorhosecondition, 
cars_checklist.batterycondition, 
cars_checklist.serpentinebeltcondition, 
cars_checklist.otherbeltscondition, 
cars_checklist.lubehoodlatch, 
cars_checklist.shockstruttest, 
cars_checklist.frontwheelbearingtest, 
cars_checklist.tierodtest, 
cars_checklist.balljointtest, 
cars_checklist.controlarmcondition, 
cars_checklist.stabilizerbarlinkcondition, 
cars_checklist.cvbootcondition, 
cars_checklist.frontbrakecondition, 
cars_checklist.frontbrakecalipers, 
cars_checklist.reardiscbrakecondition, 
cars_checklist.rearbrakecalipers, 
cars_checklist.rearstabilizerbarlinkcondition, 
cars_checklist.torqueallwheelsremoved, 
cars_checklist.exhaustsystem, 
cars_checklist.enginescancodes, 
cars_checklist.oilchange, 
cars_checklist.addoil_amount, 
cars_checklist.addoil_weight, 
cars_checklist.oilfilter_brand, 
cars_checklist.oilfilter_number, 
cars_checklist.oiltype, 
cars_checklist.finishup_checklist, 
cars_checklist.vehicle_observations, 
cars_checklist.recommended_repairs, 
cars_checklist.repairs_declined, 
cars_checklist.date_timestamp, 
cars_checklist.parts_installed, 
cars_checklist.cost, 
cars_checklist.checklist_status, 
cars_checklist.mechanics, 
cars_checklist.current_mileage
=======
cars_checklist.headlights_high, cars_checklist.headlights_low, 
cars_checklist.parkinglights_front, cars_checklist.turnsignals_front, cars_checklist.taillights, cars_checklist.turnsignals_rear, cars_checklist.brakelights, cars_checklist.backup_lights, cars_checklist.licensetabs_expiration, cars_checklist.sparetirepressure, cars_checklist.currenttirepressure_lf, cars_checklist.currenttirepressure_rf, cars_checklist.currenttirepressure_lr, cars_checklist.currenttirepressure_rr, 
cars_checklist.finaltirepressure_lf, cars_checklist.finaltirepressure_rf, cars_checklist.finaltirepressure_lr, cars_checklist.finaltirepressure_rr, cars_checklist.tirecondition_lf, cars_checklist.tirecondition_rf, cars_checklist.tirecondition_lr, cars_checklist.tirecondition_rr, 
cars_checklist.wipercondition, cars_checklist.airfiltercondition, cars_checklist.brakefluid, cars_checklist.powersteeringfluid, cars_checklist.transmissionfluid, cars_checklist.oillevel, cars_checklist.washerfluid, cars_checklist.coolantlevel, cars_checklist.coolantlevel_strength, cars_checklist.radiatorhosecondition, cars_checklist.batterycondition, cars_checklist.serpentinebeltcondition, cars_checklist.otherbeltscondition, cars_checklist.lubehoodlatch, cars_checklist.shockstruttest, cars_checklist.frontwheelbearingtest, cars_checklist.tierodtest, cars_checklist.balljointtest, cars_checklist.controlarmcondition, cars_checklist.stabilizerbarlinkcondition, cars_checklist.cvbootcondition, cars_checklist.frontbrakecondition, cars_checklist.frontbrakecalipers, cars_checklist.reardiscbrakecondition, cars_checklist.rearbrakecalipers, cars_checklist.rearstabilizerbarlinkcondition, cars_checklist.torqueallwheelsremoved, cars_checklist.exhaustsystem, cars_checklist.enginescancodes, cars_checklist.oilchange, cars_checklist.addoil_amount, cars_checklist.addoil_weight, cars_checklist.oilfilter_brand, cars_checklist.oilfilter_number, cars_checklist.oiltype, cars_checklist.finishup_checklist, cars_checklist.vehicle_observations, cars_checklist.recommended_repairs, cars_checklist.repairs_declined, cars_checklist.date_timestamp, cars_checklist.parts_installed, cars_checklist.cost, cars_checklist.checklist_status, cars_checklist.mechanics, cars_checklist.current_mileage
>>>>>>> master

--Dont delete, its a sql query to handle individual checklist pieces.

checklist.headlights_high, 
checklist.headlights_low, 
checklist.parkinglights_front, 
checklist.turnsignals_front, 
checklist.taillights, 
checklist.turnsignals_rear, 
checklist.brakelights, 
checklist.backup_lights, 
checklist.licensetabs_expiration, 
checklist.sparetirepressure, 
checklist.currenttirepressure_lf, 
checklist.currenttirepressure_rf, 
checklist.currenttirepressure_lr, 
checklist.currenttirepressure_rr, 
checklist.finaltirepressure_lf, 
checklist.finaltirepressure_rf, 
checklist.finaltirepressure_lr, 
checklist.finaltirepressure_rr, 
checklist.tirecondition_lf, 
checklist.tirecondition_rf, 
checklist.tirecondition_lr, 
checklist.tirecondition_rr, 
checklist.wipercondition, 
checklist.airfiltercondition, 
checklist.brakefluid, 
checklist.powersteeringfluid, 
checklist.transmissionfluid, 
checklist.oillevel, 
checklist.washerfluid, 
checklist.coolantlevel, 
checklist.coolantlevel_strength, 
checklist.radiatorhosecondition, 
checklist.batterycondition, 
checklist.serpentinebeltcondition, 
checklist.otherbeltscondition, 
checklist.lubehoodlatch, 
checklist.shockstruttest, 
checklist.frontwheelbearingtest, 
checklist.tierodtest, 
checklist.balljointtest, 
checklist.controlarmcondition, 
checklist.stabilizerbarlinkcondition, 
checklist.cvbootcondition, 
checklist.frontbrakecondition, 
checklist.frontbrakecalipers, 
checklist.reardiscbrakecondition, 
checklist.rearbrakecalipers, 
checklist.rearstabilizerbarlinkcondition, 
checklist.torqueallwheelsremoved, 
checklist.exhaustsystem, 
checklist.enginescancodes, 
checklist.oilchange, 
checklist.addoil_amount, 
checklist.addoil_weight, 
checklist.oilfilter_brand, 
checklist.oilfilter_number, 
checklist.oiltype, 
checklist.finishup_checklist, 
checklist.vehicle_observations, 
checklist.recommended_repairs, 
checklist.repairs_declined, 
<<<<<<< HEAD
checklist.date_timestamp, 
checklist.parts_installed, 
checklist.cost, 
checklist.checklist_status, 
checklist.mechanics, 
checklist.current_mileage
=======
checklist.parts_installed, 
checklist.cost, 
checklist.mechanics, 
checklist.current_mileage

--UPDATE
    checklist.headlights_high = $1,
    checklist.headlights_low = $2,
    checklist.parkinglights_front = $3,
    checklist.turnsignals_front = $4,
    checklist.taillights = $5,
    checklist.turnsignals_rear = $6,
    checklist.brakelights = $7,
    checklist.backup_lights = $8,
    checklist.licensetabs_expiration = $9,
    checklist.sparetirepressure = $10,
    checklist.currenttirepressure_lf = $11,
    checklist.currenttirepressure_rf = $12,
    checklist.currenttirepressure_lr = $13,
    checklist.currenttirepressure_rr = $14,
    checklist.finaltirepressure_lf = $15,
    checklist.finaltirepressure_rf = $16,
    checklist.finaltirepressure_lr = $17,
    checklist.finaltirepressure_rr = $18,
    checklist.tirecondition_lf = $19,
    checklist.tirecondition_rf = $20,
    checklist.tirecondition_lr = $21,
    checklist.tirecondition_rr = $22,
    checklist.wipercondition = $23,
    checklist.airfiltercondition = $24,
    checklist.brakefluid = $25,
    checklist.powersteeringfluid = $26,
    checklist.transmissionfluid = $27,
    checklist.oillevel = $28,
    checklist.washerfluid = $29,
    checklist.coolantlevel = $30,
    checklist.coolantlevel_strength = $31,
    checklist.radiatorhosecondition = $32,
    checklist.batterycondition = $33,
    checklist.serpentinebeltcondition = $34,
    checklist.otherbeltscondition = $35,
    checklist.lubehoodlatch = $36,
    checklist.shockstruttest = $37,
    checklist.frontwheelbearingtest = $38,
    checklist.tierodtest = $39,
    checklist.balljointtest = $40,
    checklist.controlarmcondition = $41,
    checklist.stabilizerbarlinkcondition = $42,
    checklist.cvbootcondition = $43,
    checklist.frontbrakecondition = $44,
    checklist.frontbrakecalipers = $45,
    checklist.reardiscbrakecondition = $46,
    checklist.rearbrakecalipers = $47,
    checklist.rearstabilizerbarlinkcondition = $48,
    checklist.torqueallwheelsremoved = $49,
    checklist.exhaustsystem = $50,
    checklist.enginescancodes = $51,
    checklist.oilchange = $52,
    checklist.addoil_amount = $53,
    checklist.addoil_weight = $54,
    checklist.oilfilter_brand = $55,
    checklist.oilfilter_number = $56,
    checklist.oiltype = $57,
    checklist.finishup_checklist = $58,
    checklist.vehicle_observations = $59,
    checklist.recommended_repairs = $60,
    checklist.repairs_declined = $61,
    checklist.parts_installed = $62,
    checklist.cost = $63,
    checklist.mechanics = $64,
    checklist.current_mileage = $65,
    checklist.checklist_id = $66
>>>>>>> master
